export const LANGUAGE_OPTIONS = [
  { value: "English", label: "English" },
  { value: "Hausa", label: "Hausa" },
  { value: "Igbo", label: "Igbo" },
  { value: "Yoruba", label: "Yoruba" },
  { value: "Nigerian Pidgin", label: "Nigerian Pidgin" },
  { value: "French", label: "French" },
  { value: "Arabic", label: "Arabic" },
  { value: "Spanish", label: "Spanish" },
  { value: "Portuguese", label: "Portuguese" },
  { value: "German", label: "German" },
  { value: "Italian", label: "Italian" },
  { value: "Dutch", label: "Dutch" },
  { value: "Russian", label: "Russian" },
  { value: "Turkish", label: "Turkish" },
  { value: "Swahili", label: "Swahili" },
  { value: "Amharic", label: "Amharic" },
  { value: "Somali", label: "Somali" },
  { value: "Zulu", label: "Zulu" },
  { value: "Xhosa", label: "Xhosa" },
  { value: "Kinyarwanda", label: "Kinyarwanda" },
  { value: "Lingala", label: "Lingala" },
  { value: "Akan", label: "Akan" },
  { value: "Ewe", label: "Ewe" },
  { value: "Bambara", label: "Bambara" },
  { value: "Wolof", label: "Wolof" },
  { value: "Fula", label: "Fula" },
  { value: "Shona", label: "Shona" },
  { value: "Southern Sotho", label: "Southern Sotho" },
  { value: "Tswana", label: "Tswana" },
  { value: "Tsonga", label: "Tsonga" },
  { value: "Ganda", label: "Ganda" },
  { value: "Chichewa", label: "Chichewa" },
  { value: "Hindi", label: "Hindi" },
  { value: "Urdu", label: "Urdu" },
  { value: "Bengali", label: "Bengali" },
  { value: "Tamil", label: "Tamil" },
  { value: "Telugu", label: "Telugu" },
  { value: "Marathi", label: "Marathi" },
  { value: "Gujarati", label: "Gujarati" },
  { value: "Punjabi", label: "Punjabi" },
  { value: "Chinese", label: "Chinese" },
  { value: "Japanese", label: "Japanese" },
  { value: "Korean", label: "Korean" },
];
