import type { Metadata } from "next";
import { Inter, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { GradualBlur } from "../../components";
import PublicChrome from "../../components/layout/PublicChrome";
import { ThemeScript } from "./theme-script";

const inter = Inter({
  variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <ThemeScript />
      </head>
      <body suppressHydrationWarning className={`${inter.variable} ${geistMono.variable} antialiased transition-colors duration-300`}>
        <Providers>
          {/* Page-level brand blur overlays (non-interactive, fixed) */}
          <GradualBlur target="page" preset="page-header" curve="bezier" />
          <GradualBlur target="page" preset="page-footer" curve="bezier" />

          <PublicChrome>
            {children}
          </PublicChrome>
        </Providers>
      </body>
    </html>
  );
}
